### ISSUE TITLE
[Enhancement] Show current file in explorer

### ISSUE THREAD

**Issue by llorenspujol** [sergiogc9/github-extension#35]
Whenever we are in a file by URL or by clicking in the file explorer, it would be really helpful that the file explorer would be opened with the location of this file.

## How it works now
![image](https://user-images.githubusercontent.com/18361241/165284437-b762897b-1c4c-4b2a-ae1b-04740e4f1466.png)

## How it would work
![image](https://user-images.githubusercontent.com/18361241/165284561-793c93fa-77e5-41f1-bc76-873248946e85.png)
As we see, in this case we would have the explorer opened where the file is. It would be also nice if the file is highlighted.

Let me know what do you thing. I can contribute if you tell me the steps to proceed.

Thanks and good work!

**Comment by sergiogc9** [comment]
Hey @llorenspujol !

Thanks for your suggestion and feedback! I really appreciate it.
Your suggestion was one of the features I wanted to add before releasing a stable version, hence I'm glad to tell you it's been added in version 0.3.0, which is now available at Chrome Web Store :)

The main improvements added to this issue are:
- Now the current opened file is highlighted in the sidebar.
- All upper folders in the repository tree are automatically open.
- The highlighted file changes automatically when moving over the repository tree. 
- Current file highlighting works in both code tree (i.e. viewing a repository code) and pull request view (i.e. viewing a pull request).
- Implemented in all theme modes.

Example screenshot:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/25479585/171920122-8f6019ba-cf14-4975-8d40-4a0b069fdced.png">


Let me know if you have further feedback!

**Comment by llorenspujol** [comment]
🚀🚀🚀
